name: ubuntu-newsblur
version: 0.1
summary: Newsblur Client for Ubuntu Devices
description: Client to read all your news from all over the Internet

grade: devel
confinement: strict

parts:
  newsblur:
    plugin: cmake
    configflags: [-DCMAKE_INSTALL_PREFIX=/usr, -DCMAKE_BUILD_TYPE=Debug]
    source: .
    build-packages:
      - build-essential
      - cmake
      - gettext
      - intltool
      - python3
      - qtbase5-dev
      - qtdeclarative5-dev
    stage-packages:
      - qtubuntu-desktop
      - qtdeclarative5-u1db1.0
      - qml-module-ubuntu-components
      - qml-module-ubuntu-web
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - appmenu-qt5
      - locales-all
      - suru-icon-theme
      - qtwayland5
  snapdump:
    plugin: dump
    source: snapdump
  desktoplauncher:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - dpkg-dev

apps:
  ubuntu-newsblur:
    command: desktop-launch ${SNAP}/newsblur.wrapper
    plugs: [unity7, x11, network, network-bind, opengl, browser-sandbox, wayland, upower-observe]

plugs:
  browser-sandbox:
    interface: browser-support

